-- ============================================
-- Proje     : Şirket & İK Yönetim Sistemi Veritabanı
-- Veritabanı: Oracle
-- Yazar      : Yusuf Koyuncu
-- Tarih      : 2026
-- Açıklama   : schema.sql çalıştırıldıktan sonra
--              bu dosya test verilerini ekler.
-- Çalıştırma : 1) schema.sql  2) data.sql
-- ============================================

-- USERS
INSERT INTO USERS (ID, NAME, AGE) VALUES (1, 'Ali', 22);
INSERT INTO USERS (ID, NAME, AGE) VALUES (2, 'Ayse', 24);
INSERT INTO USERS (ID, NAME, AGE) VALUES (3, 'Mehmet', 30);

-- DEPARTMENT (yoneticiler henuz eklenmedi, sonra update edilecek)
INSERT INTO DEPARTMENT (DNAME, DNUMBER, MNGSSN, MNGSTARTDATE)
VALUES ('Research', 1, NULL, DATE '2020-01-10');

INSERT INTO DEPARTMENT (DNAME, DNUMBER, MNGSSN, MNGSTARTDATE)
VALUES ('Administration', 2, NULL, DATE '2019-03-15');

-- EMPLOYEE
INSERT INTO EMPLOYEE (FNAME, LNAME, ESSN, BDATE, ADDRESS, SEX, SALARY, DEPTNO)
VALUES ('John', 'Smith', '123456789', DATE '1985-05-15', 'New York', 'M', 5000, 1);

INSERT INTO EMPLOYEE (FNAME, LNAME, ESSN, BDATE, ADDRESS, SEX, SALARY, DEPTNO)
VALUES ('Anna', 'Brown', '987654321', DATE '1990-08-21', 'Chicago', 'F', 5500, 2);

INSERT INTO EMPLOYEE (FNAME, LNAME, ESSN, BDATE, ADDRESS, SEX, SALARY, DEPTNO)
VALUES ('David', 'Wilson', '111222333', DATE '1992-11-10', 'Boston', 'M', 4200, 1);

-- Yoneticileri guncelle
UPDATE DEPARTMENT SET MNGSSN = '123456789' WHERE DNUMBER = 1;
UPDATE DEPARTMENT SET MNGSSN = '987654321' WHERE DNUMBER = 2;

COMMIT;

-- DEPT_LOCATIONS
INSERT INTO DEPT_LOCATIONS (DNUMBER, DLOCATION) VALUES (1, 'New York');
INSERT INTO DEPT_LOCATIONS (DNUMBER, DLOCATION) VALUES (1, 'Houston');
INSERT INTO DEPT_LOCATIONS (DNUMBER, DLOCATION) VALUES (2, 'Chicago');

-- PROJECT
INSERT INTO PROJECT (PNAME, PID, PLOCATION, DEPTNO)
VALUES ('ProjectA', 101, 'New York', 1);

INSERT INTO PROJECT (PNAME, PID, PLOCATION, DEPTNO)
VALUES ('ProjectB', 102, 'Chicago', 2);

-- DEPENDENT
INSERT INTO DEPENDENT (ESSN, NAME, SEX, BDATE, RELATIONSHIP)
VALUES ('123456789', 'Michael', 'M', DATE '2010-06-12', 'Son');

INSERT INTO DEPENDENT (ESSN, NAME, SEX, BDATE, RELATIONSHIP)
VALUES ('987654321', 'Sarah', 'F', DATE '2012-04-03', 'Daughter');

-- WORKS_ON
INSERT INTO WORKS_ON (ESSN, PID, HOURS) VALUES ('123456789', 101, 20);
INSERT INTO WORKS_ON (ESSN, PID, HOURS) VALUES ('111222333', 101, 15);
INSERT INTO WORKS_ON (ESSN, PID, HOURS) VALUES ('987654321', 102, 25);

-- ORDERS
INSERT INTO ORDERS (ID, USER_ID, AMOUNT) VALUES (1, 1, 120.50);
INSERT INTO ORDERS (ID, USER_ID, AMOUNT) VALUES (2, 2, 75.00);
INSERT INTO ORDERS (ID, USER_ID, AMOUNT) VALUES (3, 1, 200.00);

COMMIT;