-- ============================================
-- Proje     : Şirket & İK Yönetim Sistemi Veritabanı
-- Veritabanı: Oracle
-- Yazar      : Yusuf Koyuncu
-- Tarih      : 2026
-- Açıklama   : Çalışan, departman, proje ve sipariş
--              yönetimini kapsayan kurumsal DB şeması.
-- Çalıştırma : 1) schema.sql  2) data.sql
-- ============================================

CREATE TABLE USERS (
    ID   NUMBER PRIMARY KEY,
    NAME VARCHAR2(55),
    AGE  NUMBER
);

CREATE TABLE DEPARTMENT (
    DNAME        VARCHAR2(50) NOT NULL,
    DNUMBER      NUMBER PRIMARY KEY,
    MNGSSN       CHAR(9),
    MNGSTARTDATE DATE,
    UNIQUE (DNAME)
);

CREATE TABLE EMPLOYEE (
    FNAME   VARCHAR2(50) NOT NULL,
    LNAME   VARCHAR2(50) NOT NULL,
    ESSN    CHAR(9) PRIMARY KEY,
    BDATE   DATE,
    ADDRESS VARCHAR2(100),
    SEX     CHAR(1),
    SALARY  NUMBER(10,2),
    DEPTNO  NUMBER NOT NULL
);

CREATE TABLE DEPT_LOCATIONS (
    DNUMBER   NUMBER NOT NULL,
    DLOCATION VARCHAR2(50) NOT NULL,
    PRIMARY KEY (DNUMBER, DLOCATION)
);

CREATE TABLE PROJECT (
    PNAME     VARCHAR2(50) NOT NULL,
    PID       NUMBER PRIMARY KEY,
    PLOCATION VARCHAR2(50),
    DEPTNO    NUMBER NOT NULL,
    UNIQUE (PNAME)
);

CREATE TABLE DEPENDENT (
    ESSN         CHAR(9) NOT NULL,
    NAME         VARCHAR2(50) NOT NULL,
    SEX          CHAR(1),
    BDATE        DATE,
    RELATIONSHIP VARCHAR2(20),
    PRIMARY KEY (ESSN, NAME)
);

CREATE TABLE WORKS_ON (
    ESSN  CHAR(9) NOT NULL,
    PID   NUMBER NOT NULL,
    HOURS NUMBER(3,1) NOT NULL,
    PRIMARY KEY (ESSN, PID)
);

CREATE TABLE ORDERS (
    ID      NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    AMOUNT  NUMBER(5,2)
);

-- Foreign key kisitlamalari
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMP_DEPT
    FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT(DNUMBER);

ALTER TABLE DEPARTMENT
    ADD CONSTRAINT FK_DEPT_MANAGER
    FOREIGN KEY (MNGSSN) REFERENCES EMPLOYEE(ESSN)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DEPENDENT
    ADD CONSTRAINT FK_DEP_EMP
    FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(ESSN);

ALTER TABLE DEPT_LOCATIONS
    ADD CONSTRAINT FK_LOC_DEPT
    FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER);

ALTER TABLE PROJECT
    ADD CONSTRAINT FK_PROJECT_DEPT
    FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT(DNUMBER);

ALTER TABLE WORKS_ON
    ADD CONSTRAINT FK_WORK_EMP
    FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(ESSN);

ALTER TABLE WORKS_ON
    ADD CONSTRAINT FK_WORK_PROJECT
    FOREIGN KEY (PID) REFERENCES PROJECT(PID);

ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDER_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

-- View
-- Çalışanların detaylı raporunu gösteren sanal tablo
CREATE VIEW V_EMPLOYEE_REPORT AS
SELECT
    E.FNAME || ' ' || E.LNAME AS FULL_NAME,
    D.DNAME AS DEPARTMENT_NAME,
    E.SALARY,
    (SELECT COUNT(*) FROM DEPENDENT DEP WHERE DEP.ESSN = E.ESSN) AS TOTAL_DEPENDENTS,
    NVL(SUM(W.HOURS), 0) AS TOTAL_WORK_HOURS
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPTNO = D.DNUMBER
LEFT JOIN WORKS_ON W ON E.ESSN = W.ESSN
GROUP BY E.FNAME, E.LNAME, D.DNAME, E.SALARY, E.ESSN;

-- Trigger
-- Maaşın belirli bir sınırın altına düşmesini engelleyen güvenlik katmanı
CREATE OR REPLACE TRIGGER TRG_CHECK_SALARY
BEFORE INSERT OR UPDATE OF SALARY ON EMPLOYEE
FOR EACH ROW
BEGIN
    IF :NEW.SALARY < 2000 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Maas 2000 birimden az olamaz.');
    END IF;
END;
/

-- Procedure
-- Departmana zam yapan prosedür
CREATE OR REPLACE PROCEDURE PR_GIVE_RAISE(
    P_DEPTNO     IN NUMBER,
    P_PERCENTAGE IN NUMBER
) AS
BEGIN
    UPDATE EMPLOYEE
    SET SALARY = SALARY + (SALARY * P_PERCENTAGE / 100)
    WHERE DEPTNO = P_DEPTNO;
    COMMIT;
END;
/